### ISSUE TITLE
🐛 Bug em #4: projétil lançado duas vezes seguidas some antes da colisão

### ISSUE THREAD

**Issue by datawebcrawler** [datawebcrawler/gb_clone#7]
Quando clicamos rapidamente com mouse duas vezes seguidas são lançados dois projéteis e ambos somem antes de colidirem com o solo.
![Image](https://github.com/datawebcrawler/gb_clone/assets/56268503/289b831d-4d9e-4b8b-bc3b-3fe782c83a00)

**Comment by ivoadriel** [comment]
Basta marcar na matriz de layers a colisão projetil x projetil

**Comment by ivoadriel** [comment]
Resolvido desmarcando o layer na matriz de layers
