### ISSUE TITLE
🐛 Bug em #4: o projétil as vezes é criado e não é removido da memória.

### ISSUE THREAD

**Issue by datawebcrawler** [datawebcrawler/gb_clone#8]
Da pra ver na IDE que o projétil é criado e removido após colisão.
Mas foi encontrado caso em que o projétil não foi removido da memória.
![Image](https://github.com/datawebcrawler/gb_clone/assets/56268503/41f4b2da-330d-4a22-97ec-37a5a2276f4e)

**Comment by ivoadriel** [comment]
Resolvido, limitando o X e Y máximo do projétil.
